name: CI

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
          key: spm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}

      - name: Install Tuist & SwiftLint
        run: |
          brew update
          brew install tuist swiftlint
          tuist version
          # если в репо есть .tuist-version — подтянет закреплённую версию
          tuist install || true

      - name: Generate project with Tuist
        run: tuist generate --no-open

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build (Debug)
        shell: bash
        run: |
          set -o pipefail
          xcodebuild -version
          xcodebuild -workspace Documentor.xcworkspace \
            -scheme "Documentor-CI" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -configuration Debug \
            build | xcpretty

      - name: Test (Debug)
        shell: bash
        run: |
          set -o pipefail
          xcodebuild -workspace Documentor.xcworkspace \
            -scheme "Documentor-CI" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -configuration Debug \
            test | xcpretty
